@echo off
echo Starting Android Emulator...
start "" "C:\Users\Rio\AppData\Local\Android\Sdk\emulator\emulator.exe" -avd Pixel_9_Pro_XL
echo Waiting for device...
"C:\Users\Rio\AppData\Local\Android\Sdk\platform-tools\adb.exe" wait-for-device
echo Launching Trenx App...
"C:\Users\Rio\AppData\Local\Android\Sdk\platform-tools\adb.exe" shell am start -n com.nct.trenx/com.nct.trenx.activity.SplashActivity
echo Done!
